Fix name collision with reallocarray in FreeBSD stdlib.h
Added `sft_` prefix to match the pattern in the rest of the codebase.

I think this is the cleanest fix. I considered using the preprocessor but you cannot use a generic `#ifdef BSD` since theres no "standard" BSD, meaning you would have to manually specify each platform, i.e. `#if defined(__FreeBSD__) || defined(__OpenBSD__) || ...`. I don't think that's a good approach since it adds a whitelist/blacklist maintenance burden.

Here is the compiler error. Tested on FreeBSD 15.0.

```
deps/vendor/libschrift/schrift.c:128:14: error: static declaration of 'reallocarray' follows non-static declaration
  128 | static void *reallocarray(void *optr, size_t nmemb, size_t size);
      |              ^
/usr/include/stdlib.h:315:7: note: previous declaration is here
  315 | void    *reallocarray(void *, size_t, size_t) __result_use_check
      |          ^
deps/vendor/libschrift/schrift.c:413:1: error: static declaration of 'reallocarray' follows non-static declaration
  413 | reallocarray(void *optr, size_t nmemb, size_t size)
      | ^
/usr/include/stdlib.h:315:7: note: previous declaration is here
  315 | void    *reallocarray(void *, size_t, size_t) __result_use_check
      |          ^
2 errors generated.
```